### ISSUE TITLE
grants privs back with ShadowNinja's jail mod

### ISSUE THREAD

**Issue by stolven11** [shivajiva101/player_clean#1]
Basically whenever you jail someone and the jailed player leaves then rejoins. player_clean automatically grant the jailed player back his/hers privs, allowing them to leave jail, build, and others... (this was tested on MM-Survival)

**Comment by shivajiva101** [comment]
okay added support for jails mod, test the dev branch and let me know

**Comment by Panquesito7** [comment]
@shivajiva101, shouldn't `jails` be added as a soft dependency?
